import express from 'express';
import cors from 'cors';

const app = express();
app.use(cors());
app.use(express.json());

// Helper function to create a delay (pause) execution
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

app.post('/api/chat', async (req, res) => {
    try {
        const userMessage = req.body.message;
        const engine = req.body.engine || 'gemini'; // Default to gemini if engine is missing
        
        if (!userMessage) {
            return res.status(400).json({ error: "No message provided." });
        }

        const systemInstruction = `You are AVEN AI, a witty, energetic, and slightly sarcastic gaming tactical assistant. 
Give a highly detailed, accurate strategy answer based on the user's inquiry. Use relevant emojis and gaming humor.
Do not use markdown bolding formatting (no asterisks).
If you need to share a website link, write it out strictly as a clean clickable HTML link like this: <a href="URL" target="_blank">Link Text</a>.`;

        let botReply = "";

        if (engine === 'gpt') {
            // --- OPENAI HIGH PERFORMANCE MODE ---
            const openAiKey = process.env.OPENAI_API_KEY;
            if (!openAiKey) {
                return res.status(500).json({ error: "OpenAI API key missing on backend setup." });
            }

            const openaiUrl = 'https://api.openai.com/v1/chat/completions';
            
            const openAiResponse = await fetch(openaiUrl, {
                method: 'POST',
                headers: { 
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${openAiKey}`
                },
                body: JSON.stringify({
                    model: "gpt-4o-mini",
                    messages: [
                        { role: "system", content: systemInstruction },
                        { role: "user", content: userMessage }
                    ]
                })
            });

            const openAiData = await openAiResponse.json();
            
            if (!openAiResponse.ok) {
                throw new Error(openAiData?.error?.message || "OpenAI core error");
            }

            botReply = openAiData?.choices?.[0]?.message?.content || "No response generated by OpenAI.";

        } else {
            // --- GEMINI BALANCED MODE ---
            const geminiKey = process.env.GEMINI_API_KEY;
            if (!geminiKey) {
                return res.status(500).json({ error: "Gemini API key missing on backend setup." });
            }

            // Using the gemini-2.5-flash endpoint from your current setup
            const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${geminiKey}`;

            let response;
            let retries = 3; 
            let waitTime = 2000; 

            for (let i = 0; i < retries; i++) {
                response = await fetch(geminiUrl, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        contents: [{ parts: [{ text: userMessage }] }],
                        systemInstruction: { parts: [{ text: systemInstruction }] }
                    })
                });

                if (response.status === 429) {
                    console.warn(`Rate limit hit! Retrying in ${waitTime / 1000} seconds...`);
                    await delay(waitTime);
                    waitTime *= 2; 
                    continue; 
                }

                break;
            }

            const geminiData = await response.json();
            botReply = geminiData?.candidates?.[0]?.content?.parts?.[0]?.text || JSON.stringify(geminiData);
        }

        res.json({ reply: botReply });

    } catch (error) {
        console.error('Backend Error:', error);
        res.status(500).json({ error: 'Signal lost. Mainframe connection dropped.' });
    }
});

const PORT = process.env.PORT || 10000;
app.listen(PORT, () => {
    console.log(`AVEN AI Backend running on port ${PORT}`);
});
